# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
        key_name: terraformkey1
        instance_type: t2.micro
        image: ami-09d56f8956ab235b3
        region: us-east-1
        wait: yes
        group: default
        count: 1
        vpc_subnet_id: subnet-09bed70a71141d524
        assign_public_ip: yes
        aws_access_key: AKIPOEYUAYMTHHT42265
        aws_secret_key: TUjisSnIHj3V5ut7zLDyyer9vL9YLaqQPEtFAO4w